import {DebugSymbols} from "@scaleton/func-debug-symbols";

export const debugSymbols: DebugSymbols = {
    globals: [],
    procedures: [
        { methodId: 0, name: 'recv_internal', cellHash: '' },
        { methodId: -1, name: 'recv_external', cellHash: '' },
        { methodId: -2, name: 'run_ticktock', cellHash: '' },
        { methodId: 66763, name: 'get_full_domain', cellHash: '' },
        { methodId: 68445, name: 'get_nft_content', cellHash: '' },
        { methodId: 69506, name: 'get_telemint_token_name', cellHash: '' },
        { methodId: 72748, name: 'get_sale_data', cellHash: '' },
        { methodId: 76407, name: 'is_plugin_installed', cellHash: '' },
        { methodId: 78748, name: 'get_public_key', cellHash: '' },
        { methodId: 80293, name: 'get_owner', cellHash: '' },
        { methodId: 80697, name: 'get_auction_info', cellHash: '' },
        { methodId: 81467, name: 'get_subwallet_id', cellHash: '' },
        { methodId: 82320, name: 'get_version', cellHash: '' },
        { methodId: 83229, name: 'owner', cellHash: '' },
        { methodId: 85143, name: 'seqno', cellHash: '' },
        { methodId: 85719, name: 'royalty_params', cellHash: '' },
        { methodId: 90228, name: 'get_editor', cellHash: '' },
        { methodId: 91689, name: 'get_marketplace_address', cellHash: '' },
        { methodId: 92067, name: 'get_nft_address_by_index', cellHash: '' },
        { methodId: 93270, name: 'get_reveal_data', cellHash: '' },
        { methodId: 97026, name: 'get_wallet_data', cellHash: '' },
        { methodId: 102351, name: 'get_nft_data', cellHash: '' },
        { methodId: 102491, name: 'get_collection_data', cellHash: '' },
        { methodId: 103289, name: 'get_wallet_address', cellHash: '' },
        { methodId: 106029, name: 'get_jetton_data', cellHash: '' },
        { methodId: 107279, name: 'get_offer_data', cellHash: '' },
        { methodId: 107653, name: 'get_plugin_list', cellHash: '' },
        { methodId: 110449, name: 'get_is_closed', cellHash: '' },
        { methodId: 113617, name: 'supported_interfaces', cellHash: '' },
        { methodId: 115390, name: 'lazy_deployment_completed', cellHash: '' },
        { methodId: 116695, name: 'get_reveal_mode', cellHash: '' },
        { methodId: 118054, name: 'get_username', cellHash: '' },
        { methodId: 121275, name: 'get_abi_ipfs', cellHash: '' },
        { methodId: 122498, name: 'get_telemint_auction_state', cellHash: '' },
        { methodId: 123660, name: 'dnsresolve', cellHash: '' },
        { methodId: 128411, name: 'get_royalty_params', cellHash: '' },
        { methodId: 129619, name: 'get_telemint_auction_config', cellHash: '' },
    ],
    constants: [],
};
