import {readFileSync} from "node:fs"
import {compileFiftForSourceMap} from "../fift/compileFift"

export type ProcedureHash = string

export type SourceMap = Map<ProcedureHash, string>

/**
 * Extracts a source map from a Fift assembly file that was generated by Tact/FunC/Tolk.
 *
 * This function:
 * 1. Takes a path to the original `.fif` assembly file (with actual names)
 * 2. Combines it with a modified version of `Asm.fif` that outputs function names and hashes
 * 3. Runs Fift compilation to get the `HASH -> name` mapping from stdout
 * 4. Returns a Map that can be used by `AssemblyWriter.write()` to restore original names
 *
 * @param path Path to the original `.fif` assembly file
 * @returns Map of function hashes to their original names
 */
export async function obtainSourceMap(path: string): Promise<SourceMap> {
    const content = readFileSync(path).toString()
    const result = await compileFiftForSourceMap(content)
    return result.sourceMap
}
