import type {DebugSymbols} from "@scaleton/func-debug-symbols"

export const debugSymbols: DebugSymbols = {
    globals: [],
    procedures: [
        {methodId: 0, name: "recv_internal", cellHash: ""},
        {methodId: -1, name: "recv_external", cellHash: ""},
        {methodId: -2, name: "run_ticktock", cellHash: ""},
        {methodId: 66_763, name: "get_full_domain", cellHash: ""},
        {methodId: 68_445, name: "get_nft_content", cellHash: ""},
        {methodId: 69_506, name: "get_telemint_token_name", cellHash: ""},
        {methodId: 72_748, name: "get_sale_data", cellHash: ""},
        {methodId: 76_407, name: "is_plugin_installed", cellHash: ""},
        {methodId: 78_748, name: "get_public_key", cellHash: ""},
        {methodId: 80_293, name: "get_owner", cellHash: ""},
        {methodId: 80_697, name: "get_auction_info", cellHash: ""},
        {methodId: 81_467, name: "get_subwallet_id", cellHash: ""},
        {methodId: 82_320, name: "get_version", cellHash: ""},
        {methodId: 83_229, name: "owner", cellHash: ""},
        {methodId: 85_143, name: "seqno", cellHash: ""},
        {methodId: 85_719, name: "royalty_params", cellHash: ""},
        {methodId: 90_228, name: "get_editor", cellHash: ""},
        {methodId: 91_689, name: "get_marketplace_address", cellHash: ""},
        {methodId: 92_067, name: "get_nft_address_by_index", cellHash: ""},
        {methodId: 93_270, name: "get_reveal_data", cellHash: ""},
        {methodId: 97_026, name: "get_wallet_data", cellHash: ""},
        {methodId: 102_351, name: "get_nft_data", cellHash: ""},
        {methodId: 102_491, name: "get_collection_data", cellHash: ""},
        {methodId: 103_289, name: "get_wallet_address", cellHash: ""},
        {methodId: 106_029, name: "get_jetton_data", cellHash: ""},
        {methodId: 107_279, name: "get_offer_data", cellHash: ""},
        {methodId: 107_653, name: "get_plugin_list", cellHash: ""},
        {methodId: 110_449, name: "get_is_closed", cellHash: ""},
        {methodId: 113_617, name: "supported_interfaces", cellHash: ""},
        {methodId: 115_390, name: "lazy_deployment_completed", cellHash: ""},
        {methodId: 116_695, name: "get_reveal_mode", cellHash: ""},
        {methodId: 118_054, name: "get_username", cellHash: ""},
        {methodId: 121_275, name: "get_abi_ipfs", cellHash: ""},
        {methodId: 122_498, name: "get_telemint_auction_state", cellHash: ""},
        {methodId: 123_660, name: "dnsresolve", cellHash: ""},
        {methodId: 128_411, name: "get_royalty_params", cellHash: ""},
        {methodId: 129_619, name: "get_telemint_auction_config", cellHash: ""},
    ],
    constants: [],
}
